### ISSUE TITLE
Create .github/dependabot.yml file

### ISSUE THREAD

**Issue by Indy-rbo** [vmware/build-tools-for-vmware-aria#445]
### Description

Saw this comment https://github.com/vmware/build-tools-for-vmware-aria/pull/440#issuecomment-2393140556 and thought it should be possible to adjust these labels. I would suggest to try creating a `.github/dependabot.yml` file where you can override its defaults for things like labels and more (See the docs [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file)). This should hopefully make Dependabot fit better with your preferences.

Small example of what I mean:
```yml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "lang/java"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "lang/javascript"
```

### Alternatives

Keep changing the labels manually.
